apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-backend
  namespace: devops-service
  labels:
    app: first-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-backend
  template:
    metadata:
      labels:
        app: first-backend
    spec:
      containers:
      - name: first-backend
        image: shlee3048/fast-app:latest
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: first-backend-service
  namespace: devops-service
spec:
  selector:
    app: first-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100  
  type: NodePort
 
